spring.datasource.url=jdbc:postgresql://localhost:5432/securevault
spring.datasource.username=postgres
spring.datasource.password=Aditi@29

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aditiborle29@gmail.com
spring.mail.password=gqzb orhb znus hknx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true